folio-org/stripes-authority-components

- lib/context/AuthoritiesSearchContext.js
Search index was resetting with initial navigation segment value. so if page was opened with search mode initially and you changed to browse - search index was `keyword`. But because `keyword` is not available in browse first available option was selected.
Fixed it by setting correct default value for each navigation segment
https://user-images.githubusercontent.com/19309423/186122523-c4c3d6d3-d848-430f-8186-50fa7db7b414.mp4
[UISAUTCOMP-5](https://issues.folio.org/browse/UISAUTCOMP-5)
> UISAUTCOMP-5 Fix search index wrong initial value

- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Identifiers should be handled like this:
- bslw85033892 will be searched as `identifiers.value=="bslw85033892"`
- bslw85033892/ will be searched as `identifiers.value=="bslw85033892/"`
- bslw85033892\ will be searched as `identifiers.value==(bslw85033892\)`
[UISAUTCOMP-8](https://issues.folio.org/browse/UISAUTCOMP-8)
> UISAUTCOMP-8 Correctly handle backwards slash in identifiers

- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.test.js
- lib/BrowseFilters/BrowseFilters.test.js
- lib/SearchFilters/SearchFilters.test.js
- lib/SearchTextareaField/SearchTextareaField.js
- lib/SearchTextareaField/SearchTextareaField.test.js
- lib/context/AuthoritiesSearchContext.js
- lib/queries/useAuthorities/useAuthorities.js
- test/jest/__mock__/stripesIcon.mock.js
- test/jest/helpers/harness.js
> UISAUTCOMP-7: Fix prop types warnings in tests

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
- lib/constants/searchResultsListColumns.js
Add ability to provide additional columns to the MCL component
https://user-images.githubusercontent.com/19309423/189883443-8c6e642c-3c8b-47be-982d-a22efbe3d62e.mp4
[UISAUTCOMP-15](https://issues.folio.org/browse/UISAUTCOMP-15)
https://github.com/folio-org/ui-plugin-find-authority/pull/28
https://github.com/folio-org/ui-marc-authorities/pull/199
> UISAUTCOMP-15 Results List : Click Link icon/button to select a MARC authority record

- lib/AuthoritySourceFilter/AuthoritySourceFilter.js
- lib/AuthoritySourceFilter/AuthoritySourceFilter.test.js
- lib/BrowseFilters/BrowseFilters.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- translations/stripes-authority-components/en.json
Pass query to request for filters to get available filters for current browse
Show "Not specified" for NULL source filter option
https://user-images.githubusercontent.com/19309423/192990106-f4330fe8-9fdf-4a1e-b565-acca514137a5.mp4
[UISAUTCOMP-17](https://issues.folio.org/browse/UISAUTCOMP-17)
> UISAUTCOMP-17 Use browse query for filters, fix NULL source filter label

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
When clicking on exact match row triggers the "something went wrong" issue.
Check if row is anchor and row is not an exact match then terminate `onRowClick` behavior.
[UISAUTCOMP-21](https://issues.folio.org/browse/UISAUTCOMP-21)
> UISAUTCOMP-21

- CHANGELOG.md
- lib/AuthoritySourceFilter/AuthoritySourceFilter.test.js
- lib/FacetOptionFormatter/FacetOptionFormatter.test.js
- lib/FilterNavigation/FilterNavigation.test.js
- lib/MultiSelectionFacet/MultiSelectionFacet.test.js
- lib/ReferencesFilter/ReferencesFilter.test.js
- lib/SearchTextareaField/SearchTextareaField.test.js
Need to add a11y tests with `runAxeTest` helper from @folio/stripes-testing module.
[UISAUTCOMP-19](https://issues.folio.org/browse/UISAUTCOMP-19)
> UISAUTCOMP-19: added a11y tests

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.css
- lib/SearchResultsList/SearchResultsList.js
Fix Long browse queries don't display properly in a not-exact match placeholder
[UISAUTCOMP-22](https://issues.folio.org/browse/UISAUTCOMP-22)
> UISAUTCOMP-22 Long browse queries don't display properly in a not-exact match placeholder

- CHANGELOG.md
- lib/hooks/useAutoOpenDetailView/useAutoOpenDetailView.js
- lib/hooks/useAutoOpenDetailView/useAutoOpenDetailView.test.js
When switching between Browse and Search, for a short time `authorities` array still contains Browse results, but `navigationSegment` is now `search`, so anchor result is opened.
In Search mode, only auto-open a record when it's not an anchor
https://user-images.githubusercontent.com/19309423/199714766-09695f21-b21c-402d-b691-30a65af4f181.mp4
[UISAUTCOMP-25](https://issues.folio.org/browse/UISAUTCOMP-25)
> UISAUTCOMP-25 Fix error when switching from "Browse" to "Search", when no records were found in the browse result list

- CHANGELOG.md
- lib/hooks/useAutoOpenDetailView/useAutoOpenDetailView.js
- lib/hooks/useAutoOpenDetailView/useAutoOpenDetailView.test.js
Fix constant re-rendering after doing a search with one result.
And prevent the Detail View pane from automatically opening after it is closed in marc-authority app.
[UISAUTCOMP-30](https://issues.folio.org/browse/UISAUTCOMP-30)
[UIPFAUTH-37](https://github.com/folio-org/ui-plugin-find-authority/pull/45)
[UIMARCAUTH-204](https://github.com/folio-org/ui-marc-authorities/pull/217)
https://user-images.githubusercontent.com/77053927/203527996-a1256681-629d-4c5a-bec9-58b657b0b8ad.mp4
> UISAUTCOMP-30: Error appears when the user executes search in "MARC Authority" app

- CHANGELOG.md
- lib/context/AuthoritiesSearchContext.js
After clicking the `Reset All` button the search option has to be `keyword` for `search` lookup and empty for `browse` and filters should be reset.
[UISAUTCOMP-34](https://issues.folio.org/browse/UISAUTCOMP-34)
https://user-images.githubusercontent.com/77053927/208935348-bb9e5c19-4911-452e-98f0-1d7ef4a6dc96.mp4
> UISAUTCOMP-34: 'Reset all' button doesn't return values to default

- CHANGELOG.md
- lib/queries/useAuthority.js
Fix Reference record displaying when opening linked record
We're opening unique Authorized record, so we can ignore `headingRef` param that can be inconsistently formatted
https://user-images.githubusercontent.com/19309423/211845762-ca1da83e-b56b-43a7-b3b2-6f33a1de39ec.mp4
[UISAUTCOMP-36](https://issues.folio.org/browse/UISAUTCOMP-36)
https://github.com/folio-org/ui-quick-marc/pull/427
> UISAUTCOMP-36 Ignore headingRef when filtering authorized records

- CHANGELOG.md
- test/jest/helpers/harness.js
https://issues.folio.org/browse/UISAUTCOMP-48
Avoid private paths in stripes-core imports
> UISAUTCOMP-48: Avoid private paths in stripes-core imports

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.test.js
- lib/constants/subjectHeadingsMap.js
- test/jest/__mock__/index.js
- test/jest/__mock__/react-virtualized-auto-sizer.mock.js
Fix filtering for the `Thesaurus` facet.
Tests are failing in apps due to a recent change in `react-virtualized-auto-sizer`.
We shouldn't mock `offsetHeight` via `mockOffsetSize` because it is no longer relevant ([43](https://github.com/bvaughn/react-virtualized-auto-sizer/commit/943b6d0d4d69376f2f483201842dadbd5fc2f14d#diff-89386aae2ac82c8ec4a0d1367a57061c8abc02b01921b7db3bc139959a5778b7L163-L164)).
Just mock `react-virtualized-auto-sizer` itself.
[UISAUTCOMP-47](https://issues.folio.org/browse/UISAUTCOMP-47)
https://user-images.githubusercontent.com/77053927/228242812-257e2c42-81af-4a84-abca-bf913dbc9d88.mp4
> UISAUTCOMP-47: Fix filtering for the `Thesaurus` facet.

- CHANGELOG.md
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.js
- lib/context/AuthoritiesSearchContext.js
Use formatted `filledRows` and `query` from `useAdvancedSearch` hook to be used for initial search on page load without needing to open Advanced Search modal
https://github.com/folio-org/stripes-components/assets/19309423/43adc3b9-c1bd-43d2-bfb0-51e77e6433e3
[UISAUTCOMP-56](https://issues.folio.org/browse/UISAUTCOMP-56)
https://github.com/folio-org/stripes-components/pull/2065
> UISAUTCOMP-56 Use formatted advanced search rows for initial search.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
[UISAUTCOMP-64](https://issues.folio.org/browse/UISAUTCOMP-64)
> UISAUTCOMP-64 Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- lib/constants/headers.js
- lib/constants/index.js
- lib/queries/useAuthority.js
- lib/queries/useAuthorityMappingRules/useAuthorityMappingRules.js
- lib/queries/useMarcSource.js
- lib/temp/hooks/useTenantKy/index.js
- lib/temp/hooks/useTenantKy/useTenantKy.js
- lib/temp/hooks/useTenantKy/useTenantKy.test.js
Change tenant id to central when opening details of Shared Authority
[UISAUTCOMP-70](https://issues.folio.org/browse/UISAUTCOMP-70)
https://github.com/folio-org/ui-marc-authorities/pull/306
https://github.com/folio-org/ui-plugin-find-authority/pull/74
https://github.com/folio-org/ui-quick-marc/pull/580
> UISAUTCOMP-70 Change tenant id to central when opening details of Shared Authority

- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.test.js
- lib/BrowseFilters/BrowseFilters.js
- lib/BrowseFilters/BrowseFilters.test.js
- lib/SearchFilters/SearchFilters.js
- lib/SearchFilters/SearchFilters.test.js
Hide the Shared facet in the plugin for the shared bib record.
https://github.com/folio-org/ui-quick-marc/pull/585
https://github.com/folio-org/ui-plugin-find-authority/pull/76
[UISAUTCOMP-72](https://issues.folio.org/browse/UISAUTCOMP-72)
https://github.com/folio-org/stripes-authority-components/assets/77053927/352a1b23-c0bf-41a8-8f84-accbd24afccd
> UISAUTCOMP-72: Hide the Shared facet in the plugin for the shared bib record.

- CHANGELOG.md
- lib/constants/searchableIndexesMap.js
Fix User cannot find "MARC authority" record by "5XX" field using "Name-title" search option.
Use `saft` for Name-Title search options
https://github.com/folio-org/stripes-authority-components/assets/19309423/da50c11e-1dd2-4229-b111-5bb77580524b
[UISAUTCOMP-77](https://issues.folio.org/browse/UISAUTCOMP-77)
> UISAUTCOMP-77 Use "see from also" options for Name-Title search.

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
Fix "Reset all" button doesn't reset result pane in "MARC authority" app.
https://github.com/folio-org/stripes-authority-components/assets/19309423/42ed8544-5753-4832-84f0-0aa719348d68
[UISAUTCOMP-84](https://issues.folio.org/browse/UISAUTCOMP-84)
> UISAUTCOMP-84  Fix "Reset all" button doesn't reset result pane in "MARC authority" app.

- package.json
There is a circular dependency between `stripes-authority-components`, `ui-plugin-find-authority` and `ui-quick-marc` which blocks releasing all three modules
`ui-quick-marc` depends on `ui-plugin-find-authority`, which depends on `stripes-authority-components`, which in turn has `ui-quick-marc` dependency.
Thankfully, `ui-quick-marc` is not used anywhere in code - it was just listed as a dep, so we only need to update `package.json`
> Remove ui-quick-marc dependency

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
- lib/constants/searchResultsListColumns.js
- mocks/authorities.json
- translations/stripes-authority-components/en.json
Add a new column called `Authority source` for the browse and search results.
[UISAUTCOMP-93](https://issues.folio.org/browse/UISAUTCOMP-93)
https://github.com/folio-org/ui-plugin-find-authority/pull/86
https://github.com/folio-org/ui-marc-authorities/pull/328
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/bff2f1fc-c3db-4f80-b907-2ca0effa6978
> UISAUTCOMP-93: Add new column called Authority source for browse and search results.

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
keyword and children's subject headings search should also search by `naturalId` field
https://github.com/folio-org/stripes-authority-components/assets/19309423/638ace69-5b9b-43f2-b245-3e5937059052
[UISAUTCOMP-94](https://issues.folio.org/browse/UISAUTCOMP-94)
> UISAUTCOMP-94 MARC authority - Keyword search should search natural id.

- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
Show 'Not specified' when authority does not have a source file
[UISAUTCOMP-93](https://issues.folio.org/browse/UISAUTCOMP-93)
> UISAUTCOMP-93 follow-up: Show 'Not specified' when authority does not have a source file

- CHANGELOG.md
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/queries/useAuthoritiesBrowse/readme.md
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
Fix Facet counts changing when going Next or Prev page in Browse
Use first page query to fetch Browse facets
`useAuthoritiesBrowse` returns two query strings: `query` and `firstPageQuery`.
`query` describes search parameters that are used for browsing results for current page.
`firstPageQuery` describes search parameters that were used for browsing results for the initial page (page with anchor).
For facet requests we need to use `firstPageQuery` because if we navigate to next or previous page - the search parameters will change and we will get different facet counts.
For example, user browses `Twain, Mark`. The first page will contain the anchor and some other similar results. If the user then goes to see the previous page - Browse request will contain a parameter `headingRef < "TW, …
> UISAUTCOMP-95 Use first page Browse query for facet requests.

- CHANGELOG.md
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
Counter values and options for "Authority source", "Thesaurus" facet options do not change when changing search parameters
Need to send request to facets with current search query parameters
https://github.com/folio-org/stripes-authority-components/assets/19309423/eca0eaf7-691a-4d5c-96b3-4e67ead8e4bb
[UISAUTCOMP-101](https://issues.folio.org/browse/UISAUTCOMP-101)
https://github.com/folio-org/ui-marc-authorities/pull/345
> UISAUTCOMP-101 Counter values and options for "Authority source", "Thesaurus" facet options do not change when changing search parameters

- CHANGELOG.md
- lib/queries/useUserTenantPermissions/useUserTenantPermissions.js
- package.json
Permission-related functionality is being centralized in `@folio/stripes-core`, consolidating reliance on the `permissions` interface within that single module.
Should be merged after https://github.com/folio-org/stripes-core/pull/1453
Refs [UISAUTCOMP-117](https://folio-org.atlassian.net/browse/UISAUTCOMP-117), [STCOR-830](https://folio-org.atlassian.net/browse/UISAUTCOMP-117)
> UISAUTCOMP-117 provide deprecation notice for useUserTenantPermissions

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
SearchResultsList:
1. Show an arrow icon when a user sorts a list;
2. show a double arrow icon when a column is sortable and currently not sorted.
1. Pass `sortDirection` to MCL.
2. Pass `showSortIndicator` to MCL.
Removed failed test. It failed before this PR. MCL already shows column headers in results during loading.
https://github.com/folio-org/stripes-components/pull/2333
[UISAUTCOMP-124](https://folio-org.atlassian.net/browse/UISAUTCOMP-124)
https://github.com/user-attachments/assets/12212e48-e4e9-4ab8-937a-50105c518336
> UISAUTCOMP-124: SearchResultsList - pass `sortDirection` and `showSortIndicator` props.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- lib/utils.js
Unmapped 1xx fields will cause Authority records to have undefined `authRefType`
This PR will handle this case when `authRefType` is undefined
https://github.com/user-attachments/assets/d99143ab-0e9a-42e3-8fff-400f86c1c77d
[UISAUTCOMP-126](https://folio-org.atlassian.net/browse/UISAUTCOMP-126)
> UISAUTCOMP-126 Handle cases when `authRefType` is not defined in records.

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Change MARC authority search to "all" for full-text fields.
[UISAUTCOMP-127](https://folio-org.atlassian.net/browse/UISAUTCOMP-127)
> UISAUTCOMP-127 Change MARC authority search to "all" for full-text fields.

- CHANGELOG.md
- lib/FilterNavigation/FilterNavigation.js
- lib/FilterNavigation/FilterNavigation.test.js
- lib/SearchFilters/SearchFilters.js
- lib/context/AuthoritiesSearchContext.js
- package.json
Provide ability to subscribe to form reset event, provide `subscribeOnReset` prop to `<AcqDateRangeFilter>`.
https://github.com/user-attachments/assets/c7099922-fb98-4d73-8877-3a050479aab3
[UISAUTCOMP-130](https://folio-org.atlassian.net/browse/UISAUTCOMP-130)
https://github.com/folio-org/stripes-acq-components/pull/827
> UISAUTCOMP-130 Provide a prop to `<AcqDateRangeFilter>` to subscribe to search form resets.

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
- translations/stripes-authority-components/en.json
Handle uncaught error when a search request fails.
https://github.com/user-attachments/assets/83373222-f6ec-447f-8cec-4c409f037263
[UISAUTCOMP-133](https://folio-org.atlassian.net/browse/UISAUTCOMP-133)
> UISAUTCOMP-133 Handle uncaught error when a search request fails.

- CHANGELOG.md
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/BrowseFilters/BrowseFilters.js
- lib/BrowseFilters/BrowseFilters.test.js
Change query building process for Browse filters. Use `query=*` instead of `headingRef>=query or headingRef<query` as per BE recommendation
https://github.com/user-attachments/assets/70749f62-19ac-4962-8164-4fd68e5073fb
[UISAUTCOMP-140](http://folio-org.atlassian.net/browse/UISAUTCOMP-140)
> UISAUTCOMP-140 Change query building process for Browse filters.

- lib/queries/utils/buildAdvancedSearchQuery.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Correct the `Children's subject heading` search query to be able to search by LCCN exact match (with spaces).
[UISAUTCOMP-143](https://folio-org.atlassian.net/browse/UISAUTCOMP-143)
https://github.com/user-attachments/assets/c8878ffc-5a92-4c3c-a0df-ff5e6544042b
> UISAUTCOMP-143: Correct the `Children's subject heading` search query (follow-up).

- CHANGELOG.md
- lib/queries/useAuthority/useAuthority.js
- lib/queries/useAuthority/useAuthority.test.js
`useAuthority` hook - use `expandAll=true` parameter to fetch authority metadata. Using this parameter also includes `subjectHeadings` value in the response, but it's not used on the UI yet
[UISAUTCOMP-152](https://folio-org.atlassian.net/browse/UISAUTCOMP-152)
> UISAUTCOMP-152 `useAuthority` hook - use `expandAll=true` parameter to fetch authority metadata.
