- CHANGELOG.md
- lib/FilterNavigation/FilterNavigation.js
Browse functionality in plugin appears to be working as expected, only cleaned up one comment
https://user-images.githubusercontent.com/19309423/184852374-b5c0473d-c1a9-49d4-8a79-49d9d542e2d3.mp4
[UISAUTCOMP-5](https://issues.folio.org/browse/UISAUTCOMP-5)
> UISAUTCOMP-5 Select a MARC authority record modal >  Browse MARC authority records

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Wrap query in parentheses for identifiers search
[UISAUTCOMP-8](https://issues.folio.org/browse/UISAUTCOMP-8)
> UISAUTCOMP-8 Change marc authorities search by "identifiers.value"

- CHANGELOG.md
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.test.js
- lib/BrowseFilters/BrowseFilters.js
- lib/BrowseFilters/BrowseFilters.test.js
- lib/SearchFilters/SearchFilters.js
- lib/SearchFilters/SearchFilters.test.js
- lib/SearchResultsList/SearchResultsList.js
See [pool request](https://github.com/folio-org/ui-plugin-find-authority/pull/24).
> UISAUTCOMP-12: CLONE - Default search query change to return - authRefType=Authorized

- CHANGELOG.md
- lib/AuthoritySourceFilter/AuthoritySourceFilter.js
- lib/AuthoritySourceFilter/AuthoritySourceFilter.test.js
- lib/AuthoritySourceFilter/index.js
- lib/BrowseFilters/BrowseFilters.js
- lib/BrowseFilters/BrowseFilters.test.js
- lib/MultiSelectionFacet/MultiSelectionFacet.js
- lib/SearchFilters/SearchFilters.js
- lib/SearchFilters/SearchFilters.test.js
- lib/constants/filterConfig/filterConfig.js
- lib/index.js
- lib/queries/index.js
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthoritySourceFiles/index.js
- lib/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.js
- lib/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.test.js
- translations/stripes-authority-components/en.json
FE: MARC authority: Create an Authority source facet
https://user-images.githubusercontent.com/19309423/191938644-00d7948e-1491-40d7-9080-c87c712a643f.mp4
[UISAUTCOMP-17](https://issues.folio.org/browse/UISAUTCOMP-17)
> UISAUTCOMP-17 FE: MARC authority: Create an Authority source facet

- lib/SearchResultsList/SearchResultsList.js
Fix a11y tests in MARC Authorities app
[UISAUTCOMP-23](https://issues.folio.org/browse/UISAUTCOMP-23)
[UIMARCAUTH-188](https://issues.folio.org/browse/UIMARCAUTH-188)
> UISAUTCOMP-23: Search Results List: add non interactive headers

- CHANGELOG.md
- lib/AuthoritySourceFilter/AuthoritySourceFilter.js
- lib/AuthoritySourceFilter/AuthoritySourceFilter.test.js
- lib/BrowseFilters/BrowseFilters.js
- lib/MultiSelectionFacet/MultiSelectionFacet.js
- lib/MultiSelectionFacet/MultiSelectionFacet.test.js
- lib/SearchFilters/SearchFilters.js
- lib/SubjectHeadingsFilter/SubjectHeadingsFilter.js
- lib/SubjectHeadingsFilter/SubjectHeadingsFilter.test.js
- lib/SubjectHeadingsFilter/index.js
- lib/constants/subjectHeadingsMap.js
- lib/index.js
Fix missing labels for selected filter values that have 0 results
https://user-images.githubusercontent.com/19309423/196977840-60537202-ade2-4ccc-bcca-af1bb54b1cb3.mp4
https://github.com/folio-org/ui-marc-authorities/pull/208
[UISAUTCOMP-24](https://issues.folio.org/browse/UISAUTCOMP-24)
> UISAUTCOMP-24 MARC authority app: Authority source/Thesaurus Facet option does not display value when zero results are returned

- CHANGELOG.md
- lib/AuthoritySourceFilter/AuthoritySourceFilter.js
- lib/ReferencesFilter/ReferencesFilter.test.js
> Release v1.0.0

- lib/SearchResultsList/SearchResultsList.css
- lib/SearchResultsList/SearchResultsList.js
Improve styling of missing match item
[UISAUTCOMP-22](https://issues.folio.org/browse/UISAUTCOMP-22)
> UISAUTCOMP-22: Improve styling of missing match item

- CHANGELOG.md
- lib/constants/searchResultsListColumns.js
Add the `NUMBER_OF_TITLES` constant.
[UISAUTCOMP-32](https://issues.folio.org/browse/UISAUTCOMP-32)
[UIMARCAUTH-180](https://github.com/folio-org/ui-marc-authorities/pull/219)
> UISAUTCOMP-32: MARC authority app: Results List: Number of titles column > Link each number to return all bib records linked to the authority record 

- CHANGELOG.md
- lib/queries/useAuthority.js
Cover scenarios described in this [comment](https://issues.folio.org/browse/UIMARCAUTH-178?focusedCommentId=152869&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-152869):
- If the authority record is linked to bib records AND the Authorized/Reference value = Authorized then the delete confirmation modal indicates it is linked to bib records as expected
- If the authority record is linked to bib records AND the Authorized/Reference value = Reference then the delete confirmation modal DOES not indicate that the record is linked to bib records. IT should display the same modal as №1 if the authority record it is on is linked to a bib record.
- If the authority record is linked to bib records AND the Authorized/Reference value = Auth/Ref then the delete …
> UISAUTCOMP-35: MARC authority: Delete MARC authority record handling

- CHANGELOG.md
- package.json
bump stripes to 8.0.0
[UISAUTCOMP-37](https://issues.folio.org/browse/UISAUTCOMP-37)
[ui-marc-authorities](https://github.com/folio-org/ui-marc-authorities/pull/229)
[ui-plugin-find-authority](https://github.com/folio-org/ui-plugin-find-authority/pull/49)
> UISAUTCOMP-37: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- package.json
Align the module with API breaking change
[UISAUTCOMP-40](https://issues.folio.org/browse/UISAUTCOMP-40)
> UISAUTCOMP-40: Align the module with API breaking change

- CHANGELOG.md
- package.json
Bump quick-marc to 6.0.0
[UISAUTCOMP-39](https://issues.folio.org/browse/UISAUTCOMP-39)
> UISAUTCOMP-39: Bump quick-marc to 6.0.0

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Extend `Identifier (all)` search option with `naturalId` query.
[UISAUTCOMP-45](https://issues.folio.org/browse/UISAUTCOMP-45)
https://user-images.githubusercontent.com/77053927/221854780-ee8faa92-f9ba-4bef-8cb1-64cae21274ca.mp4
> UISAUTCOMP-45: Extend Identifier (all) search option with naturalId query.

- CHANGELOG.md
- package.json
Copy of https://github.com/folio-org/stripes-authority-components/pull/60 from fork
> UISAUTCOMP-38 unpin @rehooks/local-storage

- CHANGELOG.md
- lib/context/AuthoritiesSearchContext.js
Pre-populate search/browse box with bib subfield values 
[UISAUTCOMP-50](https://issues.folio.org/browse/UISAUTCOMP-50)
https://github.com/folio-org/ui-quick-marc/pull/506
> UISAUTCOMP-50 Pre-populate search/browse box with bib subfield values

- CHANGELOG.md
- lib/context/AuthoritiesSearchContext.js
Save values in search/browse tabs
https://user-images.githubusercontent.com/19309423/232043419-4b835ba3-a2b4-4850-ae6d-7f3c0a3a7bc5.mp4
[UISAUTCOMP-50](https://issues.folio.org/browse/UISAUTCOMP-50)
> UISAUTCOMP-50: Pre-populate search/browse box with bib subfield values 

- CHANGELOG.md
- package.json
Remove the unused `records-editor.records` interface.
[UISAUTCOMP-53](https://issues.folio.org/browse/UISAUTCOMP-53)
> UISAUTCOMP-53: Remove records-editor.records interface.

- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
- lib/hooks/index.js
- lib/hooks/useBrowseResultFocus/index.js
- lib/hooks/useBrowseResultFocus/useBrowseResultFocus.js
- lib/hooks/useBrowseResultFocus/useBrowseResultFocus.test.js
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.test.js
The focus should always be on the first result after clicking the previous/next button.
[UISAUTCOMP-54](https://issues.folio.org/browse/UISAUTCOMP-54)
[ui-marc-authorities/pull/282](https://github.com/folio-org/ui-marc-authorities/pull/282)
[ui-plugin-find-authority/pull/63](https://github.com/folio-org/ui-plugin-find-authority/pull/63)
https://user-images.githubusercontent.com/77053927/236483929-c23995e1-3b6a-49e0-a11c-0215ebbe664b.mp4
> UISAUTCOMP-54: Fix the focus of the first result for the Browse search.

- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
Remove offset reset for Browse search to fix redundant focus.
[UISAUTCOMP-54](https://issues.folio.org/browse/UISAUTCOMP-54)
https://github.com/folio-org/stripes-authority-components/assets/77053927/047e97c1-fa7c-4767-a684-a6a2f44503bd
> UISAUTCOMP-54: Remove offset reset for Browse search to fix redundant focus.

- CHANGELOG.md
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.js
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/SearchResultsList/SearchResultsList.js
- lib/context/AuthoritiesSearchContext.js
- lib/context/SelectedAuthorityRecordContextProvider.js
- lib/context/SelectedAuthorityRecordContextProvider.test.js
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.test.js
- test/jest/helpers/harness.js
Retain Search and Browse search terms.
[UISAUTCOMP-57](https://issues.folio.org/browse/UISAUTCOMP-57)
[ui-marc-authorities/pull/284](https://github.com/folio-org/ui-marc-authorities/pull/284)
[ui-plugin-find-authority/pull/66](https://github.com/folio-org/ui-plugin-find-authority/pull/66)
https://github.com/folio-org/stripes-authority-components/assets/77053927/4b26b7d9-6d78-4fd3-8294-1bf4e882401a
> UISAUTCOMP-57: Retain Search and Browse search terms.

- CHANGELOG.md
- lib/utils.js
Add optional chaining operator to avoid NPE if data lacks parsedRecord field.
[UISAUTCOMP-52](https://issues.folio.org/browse/UISAUTCOMP-52)
> UISAUTCOMP-52: Add optional chaining operator to avoid NPE if data lacks parsedRecord field

- lib/context/AuthoritiesSearchContext.js
Show always empty search option for the Browse search after resetting.
[UIPFAUTH-61](https://issues.folio.org/browse/UIPFAUTH-61?focusedCommentId=170211&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-170211)
https://github.com/folio-org/stripes-authority-components/assets/77053927/7b41dc83-8bd7-493e-90aa-6e17d8d80102
> UISAUTCOMP-57: Show always empty search option for the Browse search after resetting.

- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.js
Fix the message in the result list after resetting.
[UISAUTCOMP-58](https://issues.folio.org/browse/UISAUTCOMP-58)
https://github.com/folio-org/stripes-authority-components/assets/77053927/473d2634-1394-4dcc-a72d-fca076dff5ac
> UISAUTCOMP-58: Fix the message in the result list after resetting.

- CHANGELOG.md
- translations/stripes-authority-components/en.json
Add `Local` or `Shared` to flag MARC authorities.
https://github.com/folio-org/ui-quick-marc/pull/578
https://github.com/folio-org/ui-plugin-find-authority/pull/72
https://github.com/folio-org/ui-marc-authorities/pull/304
[UISAUTCOMP-67](https://issues.folio.org/browse/UISAUTCOMP-67)
> UISAUTCOMP-67: Add 'Local' or 'Shared' to flag MARC authorities

- CHANGELOG.md
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/AuthoritySourceFilter/AuthoritySourceFilter.js
- lib/BrowseFilters/BrowseFilters.js
- lib/SearchFilters/SearchFilters.js
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- lib/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.js
- lib/queries/useFacets/useFacets.js
Link Shared/Local MARC bib record to Shared/Local Authority record.
[UISAUTCOMP-72](https://issues.folio.org/browse/UISAUTCOMP-72)
https://github.com/folio-org/ui-quick-marc/pull/581
https://github.com/folio-org/ui-plugin-find-authority/pull/75
https://github.com/folio-org/ui-inventory/pull/2242
https://github.com/folio-org/stripes-authority-components/assets/77053927/690b9dd8-e927-42bc-b7be-19ae2c41c034
> UISAUTCOMP-72: Link Shared/Local MARC bib record to Shared/Local Authority record.

- lib/queries/useAuthorities/useAuthorities.js
Delete `cacheTime`, it is needed to highlight the edited authority record.
[UISAUTCOMP-78](https://issues.folio.org/browse/UISAUTCOMP-78)
https://github.com/folio-org/stripes-components/pull/2128
https://github.com/folio-org/stripes-authority-components/assets/77053927/9893130a-19d3-4800-9fde-bae7b6d51679
> UISAUTCOMP-79: Delete cacheTime, it is needed to highlight the edited authority record.

- CHANGELOG.md
- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
- package.json
Highlight the Browse search list row after editing the 1xx field.
[UISAUTCOMP-87](https://issues.folio.org/browse/UISAUTCOMP-87)
https://github.com/folio-org/stripes-authority-components/assets/77053927/51dd49d5-834b-4242-a403-5c9947bdffad
> UISAUTCOMP-87: Highlight the Browse search list row after editing the 1xx field.

- lib/SearchResultsList/SearchResultsList.js
- lib/SearchResultsList/SearchResultsList.test.js
Display nothing in the authority source column for the anchor.
[UISAUTCOMP-93](https://issues.folio.org/browse/UISAUTCOMP-93)
https://github.com/folio-org/stripes-authority-components/assets/77053927/6e4b3f34-4972-4c5b-a4a1-89b87adee8fa
> UISAUTCOMP-93: Display nothing in the authority source column for the anchor.

- CHANGELOG.md
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.js
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.test.js
- lib/AuthoritiesSearchPane/AuthoritiesSearchPane.js
- lib/SearchTextareaField/SearchTextareaField.js
- lib/context/AuthoritiesSearchContext.js
- lib/queries/useAuthorities/useAuthorities.js
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildAdvancedSearchQuery.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/index.js
Add Search type dropdown to Advanced search modal.
[UISAUTCOMP-97](https://issues.folio.org/browse/UISAUTCOMP-97)
https://github.com/folio-org/ui-marc-authorities/pull/340
> UISAUTCOMP-97: Add Search type dropdown to Advanced search modal.

- CHANGELOG.md
- package.json
Add `authority-source-files` interface.
https://github.com/folio-org/mod-entities-links/pull/198
[UISAUTCOMP-98](https://issues.folio.org/browse/UISAUTCOMP-98)
> UISAUTCOMP-98: Add authority-source-files interface.

- CHANGELOG.md
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.css
- lib/AuthoritiesSearchForm/AuthoritiesSearchForm.js
Re-position advanced search button when there is too little space in the search pane.
https://github.com/folio-org/stripes-authority-components/assets/19309423/68feef46-a83b-4722-acb6-60809730f83c
[UISAUTCOMP-113](https://folio-org.atlassian.net/browse/UISAUTCOMP-113)
> UISAUTCOMP-113 Re-position advanced search button when there is too little space in the search pane.

- CHANGELOG.md
- lib/SearchTextareaField/SearchTextareaField.js
Pass the `isCursorAtEnd` prop to the `TextArea` component to have a cursor at the end of the search term.
[UISAUTCOMP-123](https://folio-org.atlassian.net/browse/UISAUTCOMP-123)
> UISAUTCOMP-123: Pass the `isCursorAtEnd` prop to the `TextArea` component.

- lib/SearchResultsList/SearchResultsList.js
[UISAUTCOMP-124](https://folio-org.atlassian.net/browse/UISAUTCOMP-124)
> UISAUTCOMP-124: Pass `sortableFields` to MCL (follow-up).

- lib/queries/useAuthoritiesBrowse/useAuthoritiesBrowse.js
add optional chaining for `data.items` to `hasEmptyAnchor` to fix _intermittent_ page crash when linking.
> Add optional chaining for `data.items` to `hasEmptyAnchor`

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- lib/SearchResultsList/SearchResultsList.test.js
- lib/queries/useUserTenantPermissions/useUserTenantPermissions.js
- lib/queries/useUserTenantPermissions/useUserTenantPermissions.test.js
- package.json
When a permission set is assigned to a user, the permission names are in sub-permissions. They should also be taken into account in the `useUserTenantPermissions` hook. Permission sets are created in Settings -> Users -> Permission sets.
[UISAUTCOMP-137](https://folio-org.atlassian.net/browse/UISAUTCOMP-137)
https://github.com/user-attachments/assets/955f3384-b789-4955-9fa4-535488e9f8c8
> UISAUTCOMP-137: Return also sub permissions in `useUserTenantPermissions`.

- CHANGELOG.md
- lib/queries/useAuthorities/useAuthorities.test.js
- lib/queries/utils/buildAdvancedSearchQuery.js
- lib/queries/utils/buildQuery.js
- lib/queries/utils/buildQuery.test.js
Ability to search for a MARC authority record by exact LCCN match (with spaces) using the keyword search option.
[UISAUTCOMP-143](https://folio-org.atlassian.net/browse/UISAUTCOMP-143)
Update the keyword search query to `(keyword all "input" or naturalId=="input" or identifiers.value=="input")`.
https://github.com/user-attachments/assets/4f77f050-0334-464a-9489-3e41a7430288
> UISAUTCOMP-143: Correct keyword search.

- CHANGELOG.md
- package.json
> UISAUTCOMP-147: Upgrade `browse` to `2.0`.

- CHANGELOG.md
- lib/constants/browseHeadingTypesMap.js
- lib/constants/headingTypesValues.js
- lib/constants/searchableIndexesMap.js
- lib/queries/useAuthorities/useAuthorities.test.js
- package.json
Extend Subject search and browse to include all 1XX/4XX/5XX fields Subjects ("Named Event" and "General Subdivision").
https://folio-org.atlassian.net/browse/UISAUTCOMP-148
https://folio-org.atlassian.net/browse/UIMARCAUTH-456
https://github.com/user-attachments/assets/010d16c7-ed15-40f4-b346-58a2872f2d10
> UISAUTCOMP-148: Extend Subject search and browse to include all 1XX/4XX/5XX fields Subjects.

- CHANGELOG.md
> Release v6.0.1
